export const tiles = [
  {
    value: 5,
    row: 0,
    column: 0,
    oldRow: -1,
    mergedInto: null,
    id: 'KQ317M0iPCG7dnn5HwBCK',
  },
  {
    value: 6,
    row: 0,
    column: 1,
    oldRow: -1,
    mergedInto: null,
    id: 'CeITToqKJ4hLt5XzfQuQA',
  },
  {
    value: 6,
    row: 0,
    column: 2,
    oldRow: -1,
    mergedInto: null,
    id: 'WI9fDkLCK4bi6aUH4SGi3',
  },
  {
    value: 3,
    row: 0,
    column: 3,
    oldRow: -1,
    mergedInto: null,
    id: 'bnYWFOluVTq0v28NIlNVU',
  },
  {
    value: 8,
    row: 1,
    column: 0,
    oldRow: -1,
    mergedInto: null,
    id: 'GMqOeXXVnqhxvIG1dONHp',
  },
  {
    value: 5,
    row: 1,
    column: 1,
    oldRow: -1,
    mergedInto: null,
    id: 'VWONtGPl8u7KwUw3QvOeB',
  },
  {
    value: 1,
    row: 1,
    column: 2,
    oldRow: -1,
    mergedInto: null,
    id: 'OqbcyZrr6RvzVHDFr81Nz',
  },
  {
    value: 7,
    row: 1,
    column: 3,
    oldRow: -1,
    mergedInto: null,
    id: 'kjxU8k_dTMPzfhga1e52Z',
  },
  {
    value: 7,
    row: 2,
    column: 0,
    oldRow: -1,
    mergedInto: null,
    id: 'Hx5pVa3tErUIKZfxGSheo',
  },
  {
    value: 4,
    row: 2,
    column: 1,
    oldRow: -1,
    mergedInto: null,
    id: '39OGk3pF13ydnZTR53JBR',
  },
  {
    value: 2,
    row: 2,
    column: 2,
    oldRow: -1,
    mergedInto: null,
    id: 'xWmRL7Z9GTwNcy8JItY70',
  },
  {
    value: 4,
    row: 2,
    column: 3,
    oldRow: -1,
    mergedInto: null,
    id: 'Gz9x2LpfV0YvjpAUpB6pe',
  },
  {
    value: 9,
    row: 3,
    column: 0,
    oldRow: -1,
    mergedInto: null,
    id: 'AQZEgW_RVS3BmFxzMkugJ',
  },
  {
    value: 1,
    row: 3,
    column: 1,
    oldRow: -1,
    mergedInto: null,
    id: 'S5p7c1sYTaUXzKfUYYAf5',
  },
  {
    value: 9,
    row: 3,
    column: 2,
    oldRow: -1,
    mergedInto: null,
    id: 'XKnfhJ3YpfNLrM-lDO1Dm',
  },
  {
    value: 2,
    row: 3,
    column: 3,
    oldRow: -1,
    mergedInto: null,
    id: 'TLVZ_tlfp-M1BALvwa6AQ',
  },
];
